CREATE TABLE MEMBER(
   MID VARCHAR(20) PRIMARY KEY,
   MPW VARCHAR(20) NOT NULL,
   NAME VARCHAR(20) NOT NULL,
   ROLE VARCHAR(10) NOT NULL
);

DROP TABLE MEMBER;

INSERT INTO MEMBER VALUES('admin','1234','관리자','ADMIN');