CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	CNT INT DEFAULT 0,
	UPLOADFILE VARCHAR(50) DEFAULT 'default.jsp',
	REGDATE DATE DEFAULT SYSDATE
);

SELECT * FROM BOARD;
DROP TABLE BOARD;